var Formoid=function(){var e=function(e,t){return(e="__"+e+"__",t.length)?(this[e]=t[0],this):this[e]},t=function(e){e=e||{},this.__email__=e.email||"",this.__title__=e.title||"",this.__data__=e.data||[]};return t.prototype.email=function(t){return e.call(this,"email",arguments)},t.prototype.title=function(t){return e.call(this,"title",arguments)},t.prototype.data=function(t){return e.call(this,"data",arguments)},t.prototype.send=function(e){var t;return(t={type:"POST",data:JSON.stringify({email:this.__email__,form:{title:this.__title__,data:arguments.length?e:this.__data__}})},new Promise(function(e,o){var a=new XMLHttpRequest;a.open(t.type,"https://formoid.net/api/push"),a.onload=function(){if(200!==a.status)return o(Error("Incorrect server response."));e(a.responseText)},a.onerror=function(){var e="Failed to query the server. ";"onLine"in navigator&&!navigator.onLine?e+="No connection to the Internet.":e+="Check the connection and try again.",o(Error(e))},a.send(t.data)})).then(function(e){var t;try{t=JSON.parse(e)}catch(o){throw Error("Incorrect server response.")}if(t.error)throw Error(t.error);return t.response})},{Form:function(e){return new t(e)}}}();const formModalDOM=document.createElement("div");let formModal;formModalDOM.classList.add("modal"),formModalDOM.setAttribute("tabindex",-1),formModalDOM.style.overflow="hidden","undefined"!=typeof bootstrap?bootstrap.Tooltip.VERSION.startsWith(5)?formModalDOM.innerHTML=`
            <div class="modal-dialog d-flex align-items-center" style="">
                <div class="modal-content" style="height:auto;border-radius:0;border:none;box-shadow: 0px 0px 5px 0px rgba(0,0,0,0.25);">
                    <div class="modal-body d-flex justify-content-end flex-column align-items-end">
                        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                        <p class="display-7" style="text-align:center;width:100%;">Modal body text goes here.</p>
                    </div>
                </div>
            </div>`:formModalDOM.innerHTML=`
            <div class="modal-dialog d-flex align-items-center" style="">
                <div class="modal-content" style="height:auto;border-radius:0;border:none;box-shadow: 0px 0px 5px 0px rgba(0,0,0,0.25);">
                    <div class="modal-body d-flex justify-content-end flex-column align-items-end">
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                        <p class="display-7" style="text-align:center;width:100%;">Modal body text goes here.</p>
                    </div>
                </div>
            </div>`:$.fn.Tooltip&&(formModalDOM.innerHTML=`
        <div class="modal-dialog d-flex align-items-center" style="">
            <div class="modal-content" style="height:auto;border-radius:0;border:none;box-shadow: 0px 0px 5px 0px rgba(0,0,0,0.25);">
                <div class="modal-body d-flex justify-content-end flex-column align-items-end">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                    <p class="display-7" style="text-align:center;width:100%;">Modal body text goes here.</p>
                </div>
            </div>
        </div>`),bootstrap&&(formModal=new bootstrap.Modal(formModalDOM));var isValidEmail=function(e){return!e.value||/^([^@]+?)@(([a-z0-9]-*)*[a-z0-9]+\.)+([a-z0-9]+)$/i.test(e.value)},formComponents=document.querySelectorAll('[data-form-type="formoid"]');formComponents.forEach(function(e){var t,o="FORM"===e.tagName?e:e.querySelector("form"),a=e.querySelector("[data-form-alert]"),n=e.getAttribute("data-form-title")?e:e.querySelector("[data-form-title]"),r=e.querySelector('[type="submit"]'),l=e.querySelectorAll("[data-form-field]"),i=a.innerHTML;o.addEventListener("change",function(e){"file"===e.target.type&&e.target.files[0].size>1e6&&(formModal._element.querySelector(".modal-body p").innerText="File size must be less than 1mb",formModal._element.querySelector(".modal-content").classList.add("alert-danger"),formModal._element.querySelector(".modal-content").style.backgroundColor="#ff9966",formModal.show(),r.classList.add("btn-loading"),r.setAttribute("disabled",!0))}),o.addEventListener("submit",function(d){d.stopPropagation(),d.preventDefault(),r.classList.contains("btn-loading")||(o.classList.add("form-active"),r.classList.add("btn-loading"),r.setAttribute("disabled",!0),a.innerHTML="",t=t||Formoid.Form({email:e.querySelector("[data-form-email]").value,title:n.getAttribute("data-form-title")||n.innerText}),Promise.all(Array.prototype.map.call(l,function(e){var t;return t=e,new Promise(function(e,o){if("email"===t.getAttribute("name")&&!isValidEmail(t))return o(Error("Form is not valid"));var a=t.getAttribute("data-form-field")||t.getAttribute("name");switch(t.getAttribute("type")){case"file":var n=t.files[0];if(!n)return e();var r=new FileReader;r.onloadend=function(){e([a,r.result])},r.onerror=function(){o(r.error)},r.readAsDataURL(n);break;case"checkbox":e([a,t.checked?t.value:"No"]);break;case"radio":e(t.checked&&[a,t.value]);break;default:e([a,t.value])}})})).then(function(e){return t.send(e.filter(function(e){return e}))}).then(function(e){o.reset(),o.classList.remove("form-active"),formModal._element.querySelector(".modal-body p").innerText=i||e,formModal._element.querySelector(".modal-content").classList.add("alert-success"),formModal._element.querySelector(".modal-content").style.backgroundColor="#70c770",formModal.show()},function(e){formModal._element.querySelector(".modal-body p").innerText=e.message,formModal._element.querySelector(".modal-content").classList.add("alert-danger"),formModal._element.querySelector(".modal-content").style.backgroundColor="#ff9966"}).then(function(){r.classList.remove("btn-loading"),r.removeAttribute("disabled")}))}),l.forEach(function(e){e.addEventListener("focus",function(){r.classList.remove("btn-loading"),r.removeAttribute("disabled")})})});